version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=productsBT
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - acme

  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - acme
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: productsBT

networks:
  acme:
    external: true

volumes:
  db-data: